var goods = [
    {
        /* 手机 */
        index: 1,
        title: "手机",
        item1: [
            {
                position: "col2_1",
                brand: "Xiaomi MIX Fold 2",
                tigs: "超轻薄折叠机身设计，小米自研微水滴形态转轴",
                price: 8999,
                low: "起",
                del: "",
            },
            {
                position: "col2_2",
                brand: "Xiaomi 12S",
                tigs: "小尺寸性能旗舰 | 徕卡影像",
                price: 3999,
                low: "起",
                del: "",
            },
            {
                position: "col3_1",
                brand: "Redmi K50 至尊版",
                tigs: "骁龙8+ ｜1.5K 高清直屏",
                price: 2999,
                low: "起",
                del: "",
            },
            {
                position: "col3_2",
                brand: "Xiaomi 12 Pro 天玑版",
                tigs: "全球首发天玑9000+｜叶脉冷泵散热系统｜2K AMOLED 超视感屏 ｜5000万疾速影像",
                price: 3999,
                low: "起",
                del: "",
            },
            {
                position: "col4_1",
                brand: "Xiaomi 12S Ultra",
                tigs: "这真徕卡｜专业徕卡影像",
                price: 5999,
                low: "起",
                del: "",
            },
            {
                position: "col4_2",
                brand: "Redmi Note 11T Pro+",
                tigs: "天玑8100｜真旗舰芯",
                price: 1999,
                low: "起",
                del: "2099",
            },
            {
                position: "col5_1",
                brand: "Xiaomi 12S Pro",
                tigs: "骁龙8+ 旗舰处理器 | 徕卡影像这真徕卡｜专业徕卡影像",
                price: 4699,
                low: "起",
                del: "",
            },
            {
                position: "col5_2",
                brand: "Redmi Note 11T Pro",
                tigs: "天玑8100｜真旗舰芯",
                price: 1599,
                low: "起",
                del: "1799",
            },

        ]

    },

    /* 手表，智能穿戴 */
    {
        index: 2,
        title: "手表/智能穿戴",
        item1: [
            {

                position: "col2_1",
                brand: "Xiaomi Watch S1",
                tigs: "蓝宝石玻璃镜面 | 不锈钢中框 | 1.43”AMOLED大屏幕",
                price: 999,
                low: "起",
                del: "1099",
            },
            {
                position: "col2_2",
                brand: "Xiaomi 真无线降噪耳机 3 Pro",
                tigs: "40dB自适应降噪 ｜空间音频 ｜ HiFi高保真音质",
                price: 599,
                low: "起",
                del: "699",
            },
            {
                position: "col3_1",
                brand: "Xiaomi 真无线降噪耳机 3 Pro",
                tigs: "Xiaomi 真无线降噪耳机 3 Pro",
                price: 319,
                low: "",
                del: "499",
            },
            {
                position: "col3_2",
                brand: "Redmi Buds真无线蓝牙耳机",
                tigs: "轻巧半入耳 | 通话降噪 | 20小时长续航",
                price: 3999,
                low: "起",
                del: "",
            },
            {
                position: "col4_1",
                brand: "Redmi 手表2",
                tigs: "1.6AMD | ED大屏",
                price: 379,
                low: "",
                del: "399",
            },
            {
                position: "col4_2",
                brand: "Redmi Buds 3青春版",
                tigs: "轻巧真天线|猫耳状",
                price: 99,
                low: "",
                del: "",
            },
            {
                position: "col5_1",
                brand: "小米手环6 NFC版",
                tigs: "1.56 跑道全面彩屏",
                price: 229,
                low: "",
                del: "279",
            },

        ]
    },
    {
        index: 3,
        title: "电脑",
        item1: [
            {

                position: "col2_1",
                brand: "Redmi Book Pro 15 2022",
                tigs: "全新12代英特尔处理器",
                price: 5599,
                low: "起",
                del: "",
            },
            {
                position: "col2_2",
                brand: " Redmi Book Pro 14 2022",
                tigs: "全新12代英特尔处理器，2.5K 120Hz高清屏，可选MX550独立显卡,CNC一体精雕工艺",
                price: 5799,
                low: "起",
                del: "6299",
            },
            {
                position: "col3_1",
                brand: "Redmi G 2021 R7/RTX3050Ti/16G/51",
                tigs: "有光追，才是高性能游戏本",
                price: 5799,
                low: "起",
                del: "6299",
            },
            {
                position: "col3_2",
                brand: "小米平板5 Pro",
                tigs: " 骁龙870芯片 | 2.5K超高清｜120HZ高刷新率 ",
                price: 2299,
                low: "起",
                del: "2499",
            },
            {
                position: "col4_1",
                brand: "  Pro 14 增强版 i5 独显 - Win11",
                tigs: "2.5K超视网膜全面屏",
                price: 5599,
                low: "起",
                del: "",
            },
            {
                position: "col4_2",
                brand: " Redmi显示器23.8英寸",
                tigs: "IPS技术硬屏 | 1080P画质 ",
                price: 599,
                low: "起",
                del: "849",
            },
            {
                position: "col5_1",
                brand: "RedmiBook Pro 15 R5/16G/512G 灰	",
                tigs: "3.2K 超清视网膜全面屏 | 微米级一体精雕工艺	",
                price: 4499,
                low: "",
                del: "5299",
            },
        ]
    },
    {
        index: 4,
        title: "家电",
        item1: [
            {

                position: "col2_1",
                brand: "小米电视6 65”  OLED",
                tigs: "OLED自发光屏 | 百万级对比度 | 4.6mm超薄全面屏",
                price: 6699,
                low: "",
                del: "6999",
            },
            {
                position: "col2_2",
                brand: "米家波轮洗衣机 10kg",
                tigs: "全景玻璃阻尼上盖 防夹手",
                price: 1099,
                low: "",
                del: "1499",
            },
            {
                position: "col3_1",
                brand: "小米电视6 至尊版 65英寸",
                tigs: "百级分区背光 | 双120Hz高刷 | 4.5GB+64GB",
                price: 7199,
                low: "",
                del: "7999",
            },
            {
                position: "col3_2",
                brand: "米家冰箱无霜三门216L",
                tigs: "风冷无霜 三门三温区 ",
                price: 1499,
                low: "",
                del: "1699",
            },
            {
                position: "col4_1",
                brand: " 小米电视 ES55 2022款",
                tigs: "多分区背光 | MEMC动态补偿 | 杜比视界",
                price: 2499,
                low: "",
                del: "2999",
            },
            {
                position: "col4_2",
                brand: " 米家冰箱无霜两门186L",
                tigs: "风冷无霜 离子抗菌 ",
                price: 1299,
                low: "",
                del: "1499",
            },
            {
                position: "col5_1",
                brand: "米家直驱洗烘一体机 10kg",
                tigs: "DD直驱电机 安静护衣	",
                price: 2099,
                low: "",
                del: "2499",
            },
            {
                position: "col5_2_1",
                brand: "米家全自动滚轮机8kg",
                tigs: "",
                price: 799,
                low: "",
                del: "",
            },
        ],
        item2: [
            {

                position: "col2_1",
                brand: "小米电视4A 70英寸",
                tigs: "4K超高清 | 人工智能语音系统 | 蓝牙语音遥控器",
                price: 3199,
                low: "",
                del: "3699",
            },
            {
                position: "col2_2",
                brand: "Redmi智能电视A55",
                tigs: "4K超高清 | 智能语音 | 立体声澎湃音效",
                price: 1399,
                low: "",
                del: "1999",
            },
            {
                position: "col3_1",
                brand: "小米电视4A 60英寸",
                tigs: "4K超高清 | 语音控制 | 2+8GB大存储",
                price: 1899,
                low: "",
                del: "2799",
            },
            {
                position: "col3_2",
                brand: "Redmi MAX 86 超大平电视",
                tigs: "多分区背光|双120H",
                price: 5999,
                low: "",
                del: "7999",
            },
            {
                position: "col4_1",
                brand: " 小米电视 EA75 2022款",
                tigs: "金属全面屏 | 4K超高",
                price: 2999,
                low: "",
                del: "4199",
            },
            {
                position: "col4_2",
                brand: "小米电视 EA50 2022款",
                tigs: "金属全面屏 | 4K超高 ",
                price: 1299,
                low: "",
                del: "1899",
            },
            {
                position: "col5_1",
                brand: "小米全面屏电视65英寸",
                tigs: "4K 超高清|内置小爱音箱",
                price: 2599,
                low: "",
                del: "2999",
            },

        ]
    },
    {
        index: 5,
        title: "生活电器",
        item1: [
            {

                position: "col2_1",
                brand: "米家全能扫拖机器人",
                tigs: "色洗集尘全自动",
                price: 3999,
                low: "",
                del: "4599",
            },
            {
                position: "col2_2",
                brand: "米家扫拖机器人1T",
                tigs: "3D精准避障，扫拖不再碰撞",
                price: 999,
                low: "",
                del: "1999",
            },
            {
                position: "col3_1",
                brand: "米家扫拖机器人2C",
                tigs: "抗菌去清二合一，",
                price: 1499,
                low: "",
                del: "",
            },
            {
                position: "col3_2",
                brand: "米家扫拖机器人2",
                tigs: "经典延续，全面升级",
                price: 1499,
                low: "",
                del: "1799",
            },
            {
                position: "col4_1",
                brand: "米家扫拖机器人Pro",
                tigs: "AI智能识别 3D精准避障",
                price: 2699,
                low: "",
                del: "",
            },
            {
                position: "col4_2",
                brand: " 米家集尘扫拖机器人",
                tigs: "自动倒垃圾 ",
                price: 1999,
                low: "",
                del: "2299",
            },
            {
                position: "col5_1",
                brand: "米家无线吸尘器K10Pro",
                price: 1799,
                low: "",

            },
            {
                position: "col5_2_1",
                brand: "米家全自动滚轮机8kg",
                tigs: "",
                price: 799,
                low: "",
                del: "",
            },
        ],
        item2: [
            {

                position: "col2_1",
                brand: "小米电视4A 70英寸",
                tigs: "4K超高清 | 人工智能语音系统 | 蓝牙语音遥控器",
                price: 3199,
                low: "",
                del: "3699",
            },
            {
                position: "col2_2",
                brand: "Redmi智能电视A55",
                tigs: "4K超高清 | 智能语音 | 立体声澎湃音效",
                price: 1399,
                low: "",
                del: "1999",
            },
            {
                position: "col3_1",
                brand: "小米电视4A 60英寸",
                tigs: "4K超高清 | 语音控制 | 2+8GB大存储",
                price: 1899,
                low: "",
                del: "2799",
            },
            {
                position: "col3_2",
                brand: "Redmi MAX 86 超大平电视",
                tigs: "多分区背光|双120H",
                price: 5999,
                low: "",
                del: "7999",
            },
            {
                position: "col4_1",
                brand: " 小米电视 EA75 2022款",
                tigs: "金属全面屏 | 4K超高",
                price: 2999,
                low: "",
                del: "4199",
            },
            {
                position: "col4_2",
                brand: "小米电视 EA50 2022款",
                tigs: "金属全面屏 | 4K超高 ",
                price: 1299,
                low: "",
                del: "1899",
            },
            {
                position: "col5_1",
                brand: "小米全面屏电视65英寸",
                tigs: "4K 超高清|内置小爱音箱",
                price: 2599,
                low: "",
                del: "2999",
            },

        ]
    },
] 