// 創建一个behavior实例
let stuBehavior=Behavior({
  data:{
    name:"",
    age:"",
    sex:"",
    list:[
      {
        name:"张三",
        age:18,
        sex:"男"
      },
      {
        name:"李四",
        age:16,
        sex:"男"
      },
      {
        name:"王五",
        age:18,
        sex:"女"
      },
    ]
  },
  lifetimes:{
    created(){
      console.log("组件创建");
    },
    attached(){
      console.log("组件渲染");
    },
    ready(){
      console.log("组件渲染后");
    }
  },
  methods:{
    addUser(){
      this.data.list.push({
        name:this.data.name,
        age:this.data.age,
        sex:this.data.sex
      })
      console.log(this.data.list);
      this.setData({
        list:this.data.list,
        name:"",
        age:"",
        sex:""
      })
    }
  }
})

// 导出behavior实例
module.exports=stuBehavior;